### ISSUE TITLE
API Error -  docker-compose

### ISSUE THREAD

**Issue by jujes** [koken/docker-koken-lemp#12]
![koken-issue](https://cloud.githubusercontent.com/assets/2881017/16159625/20283db2-34c4-11e6-8b6a-2ac8ec43acaf.png)

**API Error**

The theme is not able to make contact with your Koken installation. Contact your host to see if they are blocking loopback connections.

**proxy script**

`docker run -d -p 80:80 -p 443:443 -v /etc/nginx/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro --name=proxy --restart=always jwilder/nginx-proxy`

**docker-compose.yml**

```
koken:
  restart: always
  image: koken/koken-lemp
  container_name: koken.dev
  environment:
    - VIRTUAL_HOST=koken.dev
  volumes:
    - /home/vagrant/dpl/koken.dev/src/www:/usr/share/nginx/www
    - /home/vagrant/dpl/koken.dev/src/mysql/:/var/lib/mysql
```
someone know how fix it?

**Comment by simonsmiley** [comment]
I can't get it to work either. My file looks like this:
```
koken:
  image: 'koken/koken-lemp'
  restart: always
  hostname: koken.example.com
  ports:
    - '8080:80'
  environment:
    - VIRTUAL_HOST=koken.example.com
  volumes:
    - './koken/data:/usr/share/nginx/www'
    - './koken/db:/var/lib/mysql'
```

**Comment by 5an1ty** [comment]
Log in to the admin interface, download a theme and make sure to configure your site to use that theme.

**Comment by simonsmiley** [comment]
@5an1ty downloaded an additional theme, but I can't change the settings so that koken uses it. Do you also use a docker installation with port forwarding?

**Comment by 5an1ty** [comment]
Yes, installed it regularly, I recall having a similar theme error, opened up the admin interface on yourip/admin and modified the theme settings there.

You have to go to the site section, then click on the themes button at the bottom of the page and activate the theme you selected. (I tried the theme elementary)

Not sure what this env variable does, don't think I set it:
VIRTUAL_HOST=koken.example.com

**Comment by darklow** [comment]
I was able to fix this problem by modifying `user_setup.php` and adding following line:
```php
define('LOOPBACK_HOST_HEADER', true);
```
For new build change file `deploy/php/user_setup.php`
For already deployed app file is under `storage/configuration/`

**Comment by jujes** [comment]
@darklow your advice don't solve my fix.... someone know how fix it?

thanks in advance...

I use https

```
version: '2'

services:
  web:
    image: jujes/koken:0.22.23
    hostname: koken.dev
#    volumes:
#      - $HOME/.docker/koken/html:/var/www/html
    networks:
      - docker_webgateway
      - back
    environment:
      - VIRTUAL_HOST=koken.dev
    labels:
      - "traefik.domain=koken.dev"
      - "traefik.enable=true"
      - "traefik.backend=koken.dev"
      - "traefik.frontend.rule=Host:koken.dev"
      - "traefik.docker.network=docker_webgateway"
      - "traefik.port=80"
    links:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=koken
      - MYSQL_USER=koken
      - MYSQL_PASSWORD=demo0909809
      - MYSQL_ROOT_PASSWORD=demodododo
#    volumes:
#      - $HOME/.docker/koken/mysql:/var/lib/mysql
    networks:
      - back
    restart: always
    labels:
      - "traefik.enable=false"

networks:
  docker_webgateway:
    external:
      name: docker_webgateway
  back:
    driver: bridge

```
